### ISSUE TITLE
Better to have a validation check of email id before database query

### ISSUE THREAD

**Issue by vikramsaha7** [MilanCommunity/Milan-Backend#12]
https://github.com/MilanCommunity/Milan-Backend/blob/811736276d02ab00026a6ffe4305b9ab329d0778/routes/club/Club.js#L16

**Comment by tamalCodes** [comment]
Hi @vikramsaha7 , thanks for bringing that to my notice however with respect to https://github.com/MilanCommunity/Milan/pull/1041 we will be merging the API routes too for the Login and signup of users.

So in short this file will be removed and then a single API will be there which will be responsible to handle login and register. Would you like to work on it ?

**Comment by venom-10** [comment]
I would like to work on this.

**Comment by tamalCodes** [comment]
> [!IMPORTANT]
> **The branch to make a PR to/ fork would be  `beta`**

<br/>

Hi , you can start working on the issue, assigning it to you.  Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans.

<br/>

### 📑 Checklist 


- **[Setup Guide](https://github.com/MilanCommunity/Milan/blob/main/README.md#-setting-up-the-project)** to understand the setup and the `.env`(s) for development locally.
- **[Contribution Guide](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md#contributing-guidelines)** to understand what type of PRs are accepted and how to make them.
- **[Workflow Guide](https://github.com/MilanCommunity/Milan/blob/main/docs/Workflow.md)** to understand what goes behind the scene, and why your PR doesn't get merged immediately. <br/> <br/>

**Do drop a star, Happy Opensource 💚**

**Comment by tamalCodes** [comment]
### Notice 🚩

Hi there, unfortunately, I will have to close this Issue/PR, as this issue/PR has been inactive for quite a while and there's no work going on for the same.

There might be more Issues/PR that are waiting for this to be completed - so it is better to pace things up. I generally spend/wait for 3 weeks before marking any issue as stale and closing it.

If you think that this is a mistake, please drop an email at milanhub.org@gmail.com, and we will get back to you.

Regards, 
Team Milan.
