### ISSUE TITLE
[BUG] Remove contact route from documentation

### ISSUE THREAD

**Issue by tamalCodes** [MilanCommunity/Milan-Backend#18]
### Description

We have removed the `/user/contact` route and we need to remove it from the documentation too. Here's the link to the [/user/contact in the documentation](https://milan-server.onrender.com/docs/#/User%20Contact%20API/post_user_contact) which also needs to be removed.

This can be removed from [this file](https://github.com/MilanCommunity/Milan-Backend/blob/main/config/api.yaml#L212).

### Screenshots

![image](https://github.com/MilanCommunity/Milan-Backend/assets/72851613/5ebb8f4f-2d24-4d26-863f-b9e41df72c57)

### Browser 🥦

Brave

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no).

**Comment by YuvarajSingh-0** [comment]
Just have to remove the lines in the mentioned file. Right? @tamalCodes

**Comment by tamalCodes** [comment]
Yes that is correct. However this is a very beginner friendly issue and would recommend folks with mid level knowledge to avoid it and allow folks who are starting out to OpenSource contribute to this.

**Comment by YuvarajSingh-0** [comment]
You think.... I am not a newbie in open source contribution?.... 😅

Well then.... Are there any issues that I can solve?? And BTW.... Review that footer fix PR

**Comment by tejaskh3** [comment]
Can  I go for this issue please?
