### ISSUE TITLE
💡Feature: Schema and handling for `website` and `iframe`

### ISSUE THREAD

**Issue by tamalCodes** [MilanCommunity/Milan-Backend#23]
### Description

With reference to [#1078](https://github.com/MilanCommunity/Milan/issues/1078) and [#1077](https://github.com/MilanCommunity/Milan/issues/1077), we need the schema to be updated properly.

- We would need a `website` field (not required) and a `iframe` field (not required) in the schema. 
- We need to make sure that whenever the club is signing up, the fields are updated too as per the data that is received.

### 🥦 Browser

Brave

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan-Backend/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan-Backend/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no)

**Comment by cu8code** [comment]
Assignees me this one

**Comment by tamalCodes** [comment]
Hey there we encourage 1 issue at a time, so until #27 is merged I would not assign you this, might be a mess-up. I'll keep this open for a while so that others can contribute too !

**Comment by tamalCodes** [comment]
Sure that would be awesome. You can start to work on it.

## 📑 Checklist in case you missed something

- [Local project setup, .env](https://github.com/MilanCommunity/Milan-Backend#1-setting-up-the-project-locally) for the backend.
- [Contributing guidelines](https://github.com/MilanCommunity/Milan-Backend#2-contributing-guidelines--more) to be followed.


Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans.
