### ISSUE TITLE
💡Feature:  Creating a new schema for events

### ISSUE THREAD

**Issue by tamalCodes** [MilanCommunity/Milan-Backend#26]
### Description

We need a new schema to be made for the events. These events will be shown later on, and one single club can make multiple events. The properties are mentioned below, more can be added when the PR is made (upon discussion). The file can be made directly in `routes` > `events` > `EventSchema.js`

### Properties:

- `name` : String, Required
- `about` : String, Required
- `hostclubslug` : String, Required
- `hostclubname` : String, Required
- `bannerimage` : String, Not-Required
- `thumbnailimage` : String, Required
- `mode` : String, Required
- `address` : String, Not-Required
- `city` : String, Not-Required
- `state` : String, Not-Required
- `country` : String, Not-Required
- `iframe` : String, Not-Required
- `date` : String, Required
- `time` : String, Required
- `tags` : Array of Strings, Required
- `isApproved` : Boolean, Not required, Default: false
- `createdAt` : Date, Required
- `updatedAt` : Date, Required

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan-Backend/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan-Backend/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no)

**Comment by tejaskh3** [comment]
Hey what's up @tamalCodes, if you allow me to do then I will love to do this task.

**Comment by tamalCodes** [comment]
Hi @tejaskh3 , you can start working on the issue, assigning it to you 🚀 
<br/>

## 📑 Checklist in case you missed something

- [Local project setup, .env](https://github.com/MilanCommunity/Milan-Backend#1-setting-up-the-project-locally) for the backend.
- [Contributing guidelines](https://github.com/MilanCommunity/Milan-Backend#2-contributing-guidelines--more) to be followed.


Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans.

**Comment by tejaskh3** [comment]
Thankyou!!!

**Comment by tejaskh3** [comment]
Hey @tamalCodes, I have a small doubt, here you mentioned to make schema in router "The file can be made directly in routes > events > EventSchema.js" is it correct or should i make it in schema>events>EventsSchea.js???

**Comment by tamalCodes** [comment]
> Hey @tamalCodes, I have a small doubt, here you mentioned to make schema in router "The file can be made directly in routes > events > EventSchema.js" is it correct or should i make it in schema>events>EventsSchea.js???

It's a typo from my side, it would have been  schema>events>EventsSchema.js
Sorry for the confusion, I will update the desc of the issue.

**Comment by tejaskh3** [comment]
No issues  i already got you. But don't know why I am not able to commit my changes. getting some error, and not able to resolve them yet.

**Comment by tamalCodes** [comment]
> No issues i already got you. But don't know why I am not able to commit my changes. getting some error, and not able to resolve them yet.

Please post the errors. Those maybe related to EsLint ?
Make sure you are not putting some extra gaps, or putting unused vars.

**Comment by tejaskh3** [comment]
<img width="809" alt="image" src="https://github.com/MilanCommunity/Milan-Backend/assets/98630752/8963d05d-30da-4860-9e5c-b17a9294cdb3">
This is what i am getting when trying to commit changes.

**Comment by tamalCodes** [comment]
Can you try clearing the `node_modules` and `package-lock.json` file and running `npm install` again ?

**Comment by tejaskh3** [comment]
Tried that too still not working.

**Comment by tamalCodes** [comment]
Maybe this can help ? https://github.com/typicode/husky/issues/1038
Also we love semantic commits so maybe try this too: `git commit -m "feat: added event schema"`

**Comment by tejaskh3** [comment]
Tried this as well, but not working, though the error reduced to one line only from 3, will see it after some time, after finishing this assignment. ;)

**Comment by tamalCodes** [comment]
I see.
Please see to it that you can push the code/make a PR in any way. Would be better if done hastily.

**Comment by tejaskh3** [comment]
Okay!!! doing it.
