### ISSUE TITLE
💡Feature: Events route for creating an event

### ISSUE THREAD

**Issue by tamalCodes** [MilanCommunity/Milan-Backend#33]
### Description

With the event schema made, a route must be set up that is responsible for adding an event. It would take in all the needed details and create an event in the database. 

Also add documentation for the same, in [Api.yaml file](https://github.com/MilanCommunity/Milan-Backend/blob/main/config/api.yaml) the documentation would be better for folks who are getting started.

### 🥦 Browser

Brave

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan-Backend/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan-Backend/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no)

**Comment by MahendraDani** [comment]
@tamalCodes I would like to work on this issue.

**Comment by Sundroid-ops** [comment]
@tamalCodes I am intrested in working on this.

**Comment by tamalCodes** [comment]
Hi @MahendraDani , you can start working on this issue.

## 📑 Checklist in case you missed something

- [Local project setup, .env](https://github.com/MilanCommunity/Milan-Backend#1-setting-up-the-project-locally) for the backend.
- [Contributing guidelines](https://github.com/MilanCommunity/Milan-Backend#2-contributing-guidelines--more) to be followed.


Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans.

**Comment by MahendraDani** [comment]
@tamalCodes 
I created a database on mongodb atlas and when I am connecting it to project, the following error is coming. Please help me fix this error.
![Screenshot (21)](https://github.com/MilanCommunity/Milan-Backend/assets/116940083/3e3976c5-33a7-4add-8a70-4626ed19b043)

**Comment by tamalCodes** [comment]
Can you please paste the error here, instead of a screenshot ? 
I checked, and after creating the DB, I pasted the URI in the `.env` file, which seems to work as expected.

**Comment by MahendraDani** [comment]
@tamalCodes This is the error stack.
```
dell@DESKTOP-0AQB3BG MINGW64 /d/Hacktoberfest and Hacksquad/Milanhub/Milan-Backend (main)
$ npm start

> milan-api@1.0.0 start
> nodemon index.js     

[nodemon] 3.0.1
[nodemon] to restart at any time, enter `rs`  
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,cjs,json
[nodemon] starting `node index.js`
API IS RUNNING 🚀 at port: 5000
Error connecting to MongoDB: MongooseServerSelectionError: 68100000:error:0A000438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:c:\ws\deps\openssl\openssl\ssl\record\rec_layer_s3.c:1605:SSL alert number 80

    at _handleConnectionErrors (D:\Hacktoberfest and Hacksquad\Milanhub\Milan-Backend\node_modules\mongoose\lib\connection.js:805:11)
    at NativeConnection.openUri (D:\Hacktoberfest and Hacksquad\Milanhub\Milan-Backend\node_modules\mongoose\lib\connection.js:780:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async connectToMongo (D:\Hacktoberfest and Hacksquad\Milanhub\Milan-Backend\db.js:8:5) {
  reason: TopologyDescription {
    type: 'ReplicaSetNoPrimary',
    servers: Map(3) {
      'ac-rgplvtn-shard-00-00.1w82qvl.mongodb.net:27017' => [ServerDescription],
      'ac-rgplvtn-shard-00-01.1w82qvl.mongodb.net:27017' => [ServerDescription],
      'ac-rgplvtn-shard-00-02.1w82qvl.mongodb.net:27017' => [ServerDescription]
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: 'atlas-m2tq1e-shard-0',
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: 30
  },
  code: undefined
}


```

**Comment by MahendraDani** [comment]
I have created a new database again and tested it but it still gives the same error.
Whereas on my other personal projects the database is connecting without any error. Hence I am not able to understand the cause of this error!

**Comment by tamalCodes** [comment]
I haven't seen something like this either, nor have any other users talked about the same.

- Can you check your firewall settings if something is causing an issue ?
- Can you make sure the URI is written correctly and the Network access is configured in the atlas by `0.0.0.0/0  (includes your current IP address)` ?
- Also try adding a `ssl: true,` field to the `mongoose.connect`

For me, this is working just fine. I really don't understand the issue either.

![image](https://github.com/MilanCommunity/Milan-Backend/assets/72851613/fafe6212-33a6-48b8-b447-5d830950bb01)

**Comment by MahendraDani** [comment]
@tamalCodes I solved the mongodb error. It was due to some IP Address settings.
Working on the issue now!
Thanks for the help.

**Comment by MahendraDani** [comment]
@tamalCodes I have a few doubts.
1. What should be the `api endpoint` of this route.
2. As events should be created by only registered users, so is should users be validated using `token` before creating the event. If yes, then should the `slug` of user schema be accepted as a `query` in this route?
3. What is a slug? Please give an example.

Thanks

**Comment by tamalCodes** [comment]
The route can be `/event/create`


The slug is basically the username for users, clubs, and events the slug is basically a unique identifier. For the event "Clean Plastics 2.0" their slug can be generated automatically to be `cleanplastics2.0` or the user can mention their own slug.

Currently, there is no middleware that checks the auth, so maybe we can for now design the call without any auth checking.

**Comment by MahendraDani** [comment]
Alright, Thanks
