### ISSUE TITLE
💡Feature: Get routes for events

### ISSUE THREAD

**Issue by tamalCodes** [milancommunity/Milan-Backend#34]
### Description

With the event schema made, a route must be set up that is responsible for getting the events. 
Make sure we are able to fetch all the events AND events with [the slug property](https://github.com/MilanCommunity/Milan-Backend/blob/f458a3c82372d81c7e5c031e2ea6609b49ed8f80/schema/events/EventSchema.js#L8) so that we are able to get the details of one single event.

Also add documentation for the same, in [Api.yaml file](https://github.com/MilanCommunity/Milan-Backend/blob/main/config/api.yaml) the documentation would be better for folks who are getting started.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan-Backend/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan-Backend/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no)

**Comment by MahendraDani** [comment]
@tamalCodes I would like to work on this issue.

**Comment by Sundroid-ops** [comment]
@tamalCodes I would like to work on this.

**Comment by tamalCodes** [comment]
Hi @Sundroid-ops , you can start to work on this issue.

## 📑 Checklist in case you missed something

- [Local project setup, .env](https://github.com/MilanCommunity/Milan-Backend#1-setting-up-the-project-locally) for the backend.
- [Contributing guidelines](https://github.com/MilanCommunity/Milan-Backend#2-contributing-guidelines--more) to be followed.


Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans.

**Comment by Sundroid-ops** [comment]
@tamalCodes should I create a new folder for events and work on it.

**Comment by MahendraDani** [comment]
@tamalCodes 
This issue is stale since 2 weeks.
Should I work on this issue?

**Comment by Sundroid-ops** [comment]
Sorry @MahendraDani I was just waiting for your pr to be merged I have already done my work I just have to push it.
