### ISSUE TITLE
📂Other: For Clean Code

### ISSUE THREAD

**Issue by Sundroid-ops** [MilanCommunity/Milan-Backend#35]
### Code Cleaning

Why do we need to have id here, considering other schema's id's were not assigned implicitly.
![Screenshot (64)](https://github.com/MilanCommunity/Milan-Backend/assets/94158560/d986529e-d7f6-4dd5-8458-1b2a03c08f92)

And there is a typo for timestamps here.
 
![Screenshot (65)](https://github.com/MilanCommunity/Milan-Backend/assets/94158560/7a6107bd-ecc3-4ac7-927f-bd1311da549e)

I would like to fix this.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan-Backend/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan-Backend/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
Hi @Sundroid-ops , even though we have a product schema and stuffs, we will ignore this for now as you can see in https://milanhub.org/shop we are still yet to do it, so for now let us move on with other issues at hand, while we keep this closed.
