### ISSUE TITLE
Bug: Issue in sending data to GoogleOauth as Custom input

### ISSUE THREAD

**Issue by RajBhattacharyya** [MilanCommunity/Milan-Backend#41]
### Description

**Description:**

Issue:

- UserType input not going to the database as custom input by google auth

Expected Behavior:

- User able to set the userType during creation of user account
- Google auth take that userInput and send that to the database

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan-Backend/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan-Backend/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by tamalCodes** [comment]
Sound great, please go ahead.


## 📑 Checklist in case you missed something

- [Local project setup, .env](https://github.com/MilanCommunity/Milan-Backend#1-setting-up-the-project-locally) for the backend.
- [Contributing guidelines](https://github.com/MilanCommunity/Milan-Backend#2-contributing-guidelines--more) to be followed.


Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans.
